### ISSUE TITLE
<br> being added without reason

### ISSUE THREAD

**Issue by rolero** [niteosoft/simplejobscript#6]
When adding text in the tinyMCE editor for chaning the content on the "static" pages  a `<br>`  element is being added when using `<p>`,`<ol>`, and `<li>`. I did not add these element in the TinyMCE editor (backend). I am also not able to remove them.

An example:
![image](https://user-images.githubusercontent.com/2805313/60321903-b024b400-99b0-11e9-9c7d-0a2ecb41009e.png)

**Comment by rolero** [comment]
Here also a printscreen of how the content looks in the backend:
![image](https://user-images.githubusercontent.com/2805313/60321977-efeb9b80-99b0-11e9-8d65-2a7a9b77a268.png)

**Comment by niteosoft** [comment]
Editor basically replaces new lines with <br> HTML code. So should not add extra new lines rather than just replace the existing ones.

When you look at:
https://www.88careers.com/privacy-policy
(default static page with a list) you can see an example of numbered list that shows up correctly.
Please try to follow the same pattern as this page and your issues should be resolved.
